extends: [eslint:recommended, plugin:react/recommended]
plugins:
  - standard
  - promise
  - react
env:
  browser: true
  node: true
  es6: true
  jest: true
globals:
  shallow: false
parserOptions:
  ecmaVersion: 6
  sourceType: module
  allowImportExportEverywhere: true
  ecmaFeatures:
    jsx: true
    modules: true
rules:
  semi: ['error', 'always', {omitLastInOneLineBlock: true}]
